#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1

PROG="/usr/bin/led-modem-controller"
NAME="led-modem-controller"

start_service() {
    [ -x "$PROG" ] || {
        logger -t led-modem-controller "Program not found or not executable: $PROG"
        return 1
    }

    logger -t led-modem-controller "Starting service"

    procd_open_instance
    procd_set_param command "$PROG" start
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    logger -t led-modem-controller "Service started"
}

stop_service() {
    logger -t led-modem-controller "Stopping service"
    [ -x "$PROG" ] && "$PROG" stop
}

service_triggers() {
    procd_add_reload_trigger "led-modem-controller"
}

reload_service() {
    stop
    start
}
